//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicketAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_tab_region
    {
        public long region_cod_region { get; set; }
        public string region_dsc_region { get; set; }
        public Nullable<System.DateTime> region_fec_ini { get; set; }
        public Nullable<System.DateTime> region_fec_fin { get; set; }
    }
}
