//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicketAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_tab_comuna
    {
        public long comuna_cod_comuna { get; set; }
        public string comuna_nom_comuna { get; set; }
        public string comuna_ciudad_comuna { get; set; }
        public long comuna_cod_region { get; set; }
    }
}
