//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicketAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_tab_persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mt_tab_persona()
        {
            this.mt_tab_usuario = new HashSet<mt_tab_usuario>();
        }
    
        public long persona_cod_persona { get; set; }
        public decimal persona_num_rut { get; set; }
        public string persona_num_dv { get; set; }
        public string persona_dsc_nombre { get; set; }
        public string persona_dsc_appaterno { get; set; }
        public string persona_dsc_apmaterno { get; set; }
        public Nullable<System.DateTime> persona_fec_nacimiento { get; set; }
        public string persona_num_fono { get; set; }
        public string persona_num_celular { get; set; }
        public string persona_dsc_mail { get; set; }
        public Nullable<long> direccion_cod_direccion { get; set; }
    
        public virtual mt_tab_direccion mt_tab_direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mt_tab_usuario> mt_tab_usuario { get; set; }
    }
}
