//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicketAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_tab_rolusua
    {
        public long rolusua_cod_rolusua { get; set; }
        public Nullable<long> rol_cod_rol { get; set; }
        public Nullable<long> usuario_cod_usuario { get; set; }
        public Nullable<System.DateTime> rolusua_fec_ini { get; set; }
        public Nullable<System.DateTime> rolusua_fec_fin { get; set; }
    }
}
