//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicketAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mt_tab_comuna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mt_tab_comuna()
        {
            this.mt_tab_direccion = new HashSet<mt_tab_direccion>();
        }
    
        public long comuna_cod_comuna { get; set; }
        public Nullable<long> usuario_cod_estado { get; set; }
        public string usuario_cod_password { get; set; }
        public string usuario_dsc_area { get; set; }
        public Nullable<long> persona_cod_persona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mt_tab_direccion> mt_tab_direccion { get; set; }
    }
}
